CinemaSystem/Models/Screening.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
#nullable disable

namespace CinemaSystem.Models
{
    public partial class Screening
    {
        public Screening()
        {
            Reservations = new HashSet<Reservation>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ScreeningId { get; set; }
        public int? MovieId { get; set; }
        public int? AudithoriumId { get; set; }
        public TimeSpan? ScreeningStart { get; set; }
        public int? Cost { get; set; }

        public virtual Audithorium Audithorium { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}

CinemaSystem/Controllers/ScreeningController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using CinemaSystem.Models;
using CinemaSystem.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CinemaSystem.Controllers
{
    public class ScreeningController: Controller { 

        private CinemaDBContext db;
        public ScreeningController(CinemaDBContext context)
        {
            db = context;
        }

        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> ScreeningMain()
        {

            return View(await db.Screenings.Include(r => r.Audithorium).Include(r1=>r1.Movie).ToListAsync());
        }

        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> Create()
        {
            var vm = new ScreeningModel();
            vm.Movies = db.Movies
                                  .Select(a => new SelectListItem()
                                  {
                                      Value = a.MovieId.ToString(),
                                      Text = a.Title
                                  })
                                  .ToList();
            vm.Audithoriums = db.Audithoria
                      .Select(a => new SelectListItem()
                      {
                          Value = a.AudithoriumId.ToString(),
                          Text = a.Name
                      })
                      .ToList();
            ViewBag.vm = vm.Movies;
            ViewBag.vm1 = vm.Audithoriums;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> Create(Screening screening)
        {

            db.Screenings.Add(screening);
            await db.SaveChangesAsync();
            return RedirectToAction("ScreeningMain");
        }

        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Screening screening = await db.Screenings.FirstOrDefaultAsync(p => p.ScreeningId == id);
                if (screening != null)
                {
                    var vm = new ScreeningModel();
                    vm.Movies = db.Movies
                                          .Select(a => new SelectListItem()
                                          {
                                              Value = a.MovieId.ToString(),
                                              Text = a.Title
                                          })
                                          .ToList();
                    vm.Audithoriums = db.Audithoria
                              .Select(a => new SelectListItem()
                              {
                                  Value = a.AudithoriumId.ToString(),
                                  Text = a.Name
                              })
                              .ToList();
                    ViewBag.vm = vm.Movies;
                    ViewBag.vm1 = vm.Audithoriums;
                    return View(screening);
                }
            }
            return NotFound();
        }
        [HttpPost]
        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> Edit(Screening screening)
        {
            db.Screenings.Update(screening);
            await db.SaveChangesAsync();
            return RedirectToAction("ScreeningMain");
        }

        [HttpGet]
        [ActionName("Delete")]
        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Screening screening = await db.Screenings.FirstOrDefaultAsync(p => p.ScreeningId == id);
                if (screening != null)
                    return View(screening);
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Director, Customer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Screening screening = await db.Screenings.FirstOrDefaultAsync(p => p.ScreeningId == id);
                if (screening != null)
                {
                    db.Screenings.Remove(screening);
                    await db.SaveChangesAsync();
                    return RedirectToAction("ScreeningMain");
                }
            }
            return NotFound();
        }

    }

}

CinemaSystem/Views/Screening/Create.cshtml
@using CinemaSystem.ViewModels
@model CinemaSystem.Models.Screening

@{
    ViewBag.Title = "Добавление сеанса";
}
<form asp-action="create" asp-controller="screening">
    <div class="form-group">
        <label asp-for="MovieId" class="control-label">Фильм</label>
        <select asp-for="MovieId" asp-items="ViewBag.vm"></select>
    </div>
    <div class="form-group">
        <label asp-for="AudithoriumId" class="control-label">Зал</label>
        <select asp-for="AudithoriumId" asp-items="ViewBag.vm1"></select>
    </div>
    <div class="form-group">
        <label asp-for="ScreeningStart" class="control-label">Начало</label>
        <input type="text" asp-for="ScreeningStart" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Cost" class="control-label">Цена</label>
        <input type="text" asp-for="Cost" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

CinemaSystem/Views/Screening/Delete.cshtml
@model CinemaSystem.Models.Screening
@{
    ViewBag.Title = "Удаление сеанса";
}

<div>
    <dl class="dl-horizontal">
        <dt>Название</dt>
        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>
  

    </dl>

    <div>
        <form asp-controller="Screening" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

CinemaSystem/Views/Screening/Edit.cshtml
@using CinemaSystem.ViewModels
@model CinemaSystem.Models.Screening

@{
    ViewBag.Title = "Редактирование сеанса";
}
<form asp-action="edit" asp-controller="screening" asp-route-id="@Model.ScreeningId">
    <div class="form-group">
        <label asp-for="MovieId" class="control-label">Фильм</label>
        <select asp-for="MovieId" asp-items="ViewBag.vm"></select>
    </div>
    <div class="form-group">
        <label asp-for="AudithoriumId" class="control-label">Зал</label>
        <select asp-for="AudithoriumId" asp-items="ViewBag.vm1"></select>
    </div>
    <div class="form-group">
        <label asp-for="ScreeningStart" class="control-label">Начало</label>
        <input type="text" asp-for="ScreeningStart" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Cost" class="control-label">Цена</label>
        <input type="text" asp-for="Cost" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

CinemaSystem/Views/Screening/ScreeningMain.cshtml
@model IEnumerable<CinemaSystem.Models.Screening>
@{
    ViewBag.Title = "Все сеансы";
}
<a asp-action="Create">Добавить новый сеанс</a>
<table class="table">
    <tr><td>Фильм</td><td>Зал</td><td>Начало</td><td>Цена</td></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Movie.Title</td>
            <td>@item.Audithorium.Name</td>
            <td>@item.ScreeningStart</td>
            <td>@item.Cost</td>
            <td>
                <a asp-action="Edit" asp-controller="Screening" asp-route-id="@item.ScreeningId">Изменить</a> |
                <a asp-action="Delete" asp-controller="Screening'" asp-route-id="@item.ScreeningId">Удалить</a>
            </td>
        </tr>
    }
</table>